import type {
  Location,
  Sector,
  DarshanQueue,
  ParkingArea,
  Announcement,
  EmergencyPoint,
  RouteClosure,
  LocationCategory
} from '@/types';

export const DEMO_CATEGORIES: LocationCategory[] = [
  { id: 'cat-darshan', slug: 'darshan', name: 'Darshan & Queues', name_te: 'దర్శనం మరియు క్యూలు', icon: 'Eye', color: '#9b1b30', is_primary: true, display_order: 1, created_at: new Date().toISOString() },
  { id: 'cat-parking', slug: 'parking', name: 'Vehicle Parking', name_te: 'వాహన పార్కింగ్', icon: 'Car', color: '#2563eb', is_primary: true, display_order: 2, created_at: new Date().toISOString() },
  { id: 'cat-food', slug: 'food', name: 'Annadanam & Meals', name_te: 'అన్నదానం మరియు భోజనం', icon: 'Utensils', color: '#ea580c', is_primary: true, display_order: 3, created_at: new Date().toISOString() },
  { id: 'cat-medical', slug: 'medical', name: 'Medical & First Aid', name_te: 'వైద్యం మరియు ప్రథమ చికిత్స', icon: 'Plus', color: '#dc2626', is_primary: true, display_order: 4, created_at: new Date().toISOString() },
  { id: 'cat-bus', slug: 'bus', name: 'RTC Shuttle & Bus', name_te: 'RTC షటిల్ మరియు బస్సు', icon: 'Bus', color: '#059669', is_primary: true, display_order: 5, created_at: new Date().toISOString() },
  { id: 'cat-ghat', slug: 'ghat', name: 'River Ghats & Bathing', name_te: 'నది ఘాట్లు మరియు స్నాన ఘట్టాలు', icon: 'Waves', color: '#0284c7', is_primary: false, display_order: 6, created_at: new Date().toISOString() },
];

export const DEMO_SECTORS: Sector[] = [
  {
    id: 'sec-1',
    name: 'Sector 1 — Indrakeeladri Hill Top Sanctum',
    name_te: 'సెక్టార్ 1 — ఇంద్రకీలాద్రి కొండపై గర్భగుడి',
    description: 'Main temple shrine, sanctum sanctorum and sanctified parikrama.',
    description_te: 'ప్రధాన ఆలయ గర్భాలయం మరియు పరిక్రమ ప్రాంగణం.',
    slug: 'indrakeeladri-hill-top',
    geometry: null,
    centroid: { type: 'Point', coordinates: [80.6238, 16.5148] },
    status: 'ACTIVE',
    crowd_level: 'HIGH',
    crowd_updated_at: new Date().toISOString(),
    crowd_source: 'CAMERA',
    metadata: {},
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-2',
    name: 'Sector 2 — Ghat Road Queue Complex',
    name_te: 'సెక్టార్ 2 — ఘాట్ రోడ్ క్యూ కాంప్లెక్స్',
    description: 'Covered queue lines along Indrakeeladri Ghat Road.',
    description_te: 'ఇంద్రకీలాద్రి ఘాట్ రోడ్ వెంబడి ఉన్న రక్షిత క్యూ లైన్లు.',
    slug: 'ghat-road-queue',
    geometry: null,
    centroid: { type: 'Point', coordinates: [80.6235, 16.5140] },
    status: 'ACTIVE',
    crowd_level: 'CRITICAL',
    crowd_updated_at: new Date().toISOString(),
    crowd_source: 'CAMERA',
    metadata: {},
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-3',
    name: 'Sector 3 — Hill Base & Annadanam Complex',
    name_te: 'సెక్టార్ 3 — కొండ దిగువ మరియు అన్నదానం కాంప్లెక్స్',
    description: 'Foot-hill entrance, shoe stands, luggage counters and Annadanam.',
    description_te: 'కొండ దిగువ ప్రవేశ ద్వారం, పాదరక్షల స్టాండ్ మరియు అన్నదాన భవనం.',
    slug: 'hill-base-annadanam',
    geometry: null,
    centroid: { type: 'Point', coordinates: [80.6225, 16.5160] },
    status: 'ACTIVE',
    crowd_level: 'NORMAL',
    crowd_updated_at: new Date().toISOString(),
    crowd_source: 'MANUAL',
    metadata: {},
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-4',
    name: 'Sector 4 — Krishna River Bathing Ghats',
    name_te: 'సెక్టార్ 4 — కృష్ణా నది స్నాన ఘట్టాలు',
    description: 'Bhavani Ghat, Punnami Ghat, dressing rooms and holy bath areas.',
    description_te: 'భవాని ఘాట్, పున్నమి ఘాట్ మరియు పవిత్ర స్నాన ప్రాంతాలు.',
    slug: 'krishna-river-ghats',
    geometry: null,
    centroid: { type: 'Point', coordinates: [80.6210, 16.5180] },
    status: 'ACTIVE',
    crowd_level: 'LOW',
    crowd_updated_at: new Date().toISOString(),
    crowd_source: 'ESTIMATE',
    metadata: {},
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-5',
    name: 'Sector 5 — Outer Transit & Parking Hubs',
    name_te: 'సెక్టార్ 5 — బాహ్య రవాణా మరియు పార్కింగ్ కేంద్రాలు',
    description: 'NH65 parking grounds and free APSRTC shuttle hubs.',
    description_te: 'NH65 పార్కింగ్ స్థలాలు మరియు ఉచిత RTC షటిల్ స్టేషన్లు.',
    slug: 'outer-parking-hubs',
    geometry: null,
    centroid: { type: 'Point', coordinates: [80.6190, 16.5130] },
    status: 'ACTIVE',
    crowd_level: 'NORMAL',
    crowd_updated_at: new Date().toISOString(),
    crowd_source: 'ESTIMATE',
    metadata: {},
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_LOCATIONS: Location[] = [
  {
    id: '56b5d4a0-4a2c-427a-bc52-ff93eb120ddf',
    name: 'Main Darshan Entry (Indrakeeladri Hill Top)',
    name_te: 'ప్రధాన దర్శన ప్రవేశం (ఇంద్రకీలాద్రి కొండపై)',
    category_id: 'cat-darshan',
    sector_id: 'sec-1',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6238, 16.5148] },
    status: 'ACTIVE',
    description: 'Primary entry point to the inner sanctum of Sri Kanaka Durga Ammavaru.',
    description_te: 'శ్రీ కనకదుర్గ అమ్మవారి అంతరాలయ ప్రధాన దర్శన ద్వారం.',
    address: 'Indrakeeladri Hill, Mallikarjunapeta, Vijayawada',
    address_te: 'ఇంద్రకీలాద్రి కొండ, మల్లికార్జునపేట, విజయవాడ',
    contact_phone: '0866-2423600',
    contact_name: 'Temple Helpdesk',
    operating_hours: '03:00 AM - 11:00 PM',
    capacity: 25000,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[0],
    sector: DEMO_SECTORS[0],
  },
  {
    id: 'loc-ghat-queue',
    name: 'Ghat Road Queue Complex Entry',
    name_te: 'ఘాట్ రోడ్ క్యూ కాంప్లెక్స్ ప్రవేశం',
    category_id: 'cat-darshan',
    sector_id: 'sec-2',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6235, 16.5140] },
    status: 'ACTIVE',
    description: 'Special ₹100 and ₹300 queue line entrance along shaded ghat steps.',
    description_te: 'ప్రత్యేక ₹100 మరియు ₹300 టికెట్ క్యూ లైన్ ప్రవేశ మార్గం.',
    address: 'Ghat Road curve 2, Indrakeeladri',
    address_te: 'ఘాట్ రోడ్ మలుపు 2, ఇంద్రకీలాద్రి',
    contact_phone: '0866-2423600',
    contact_name: 'Queue Incharge',
    operating_hours: '04:00 AM - 10:30 PM',
    capacity: 15000,
    is_accessible: false,
    is_demo_data: true,
    metadata: {},
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[0],
    sector: DEMO_SECTORS[1],
  },
  {
    id: 'loc-annadanam',
    name: '24x7 Maha Annadanam Bhavan',
    name_te: '24x7 మహా అన్నదాన భవనం',
    category_id: 'cat-food',
    sector_id: 'sec-3',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6225, 16.5160] },
    status: 'ACTIVE',
    description: 'Free sanctified vegetarian meals served continuously for all visiting pilgrims.',
    description_te: 'భక్తులందరికీ నిరంతరంగా ఉచిత రుచికరమైన మహా అన్నప్రసాద వితరణ.',
    address: 'Opposite Hill Steps Entrance, Vijayawada',
    address_te: 'కొండ మెట్ల ప్రవేశ ద్వారం ఎదురుగా, విజయవాడ',
    contact_phone: '0866-2423620',
    contact_name: 'Annadanam Manager',
    operating_hours: '24 Hours Open',
    capacity: 5000,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[2],
    sector: DEMO_SECTORS[2],
  },
  {
    id: 'loc-bhavani-ghat',
    name: 'Bhavani Ghat Holy Bathing & Transit',
    name_te: 'భవాని ఘాట్ పవిత్ర స్నాన ఘట్టం & రవాణా',
    category_id: 'cat-ghat',
    sector_id: 'sec-4',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6210, 16.5180] },
    status: 'ACTIVE',
    description: 'Sacred Krishna river bathing ghat with locker rooms and shuttle pickup.',
    description_te: 'కృష్ణా నది పవిత్ర స్నాన ఘాట్, దుస్తులు మార్చుకునే గదులు మరియు బస్సు పాయింట్.',
    address: 'Krishna Riverbank, Near Prakasam Barrage',
    address_te: 'కృష్ణా నది ఒడ్డు, ప్రకాశం బ్యారేజీ సమీపంలో',
    contact_phone: '0866-2423630',
    contact_name: 'Ghat Officer',
    operating_hours: '24 Hours Open',
    capacity: 20000,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[5],
    sector: DEMO_SECTORS[3],
  },
  {
    id: 'loc-punnami-ghat',
    name: 'Punnami Ghat Parking & Shuttle Hub',
    name_te: 'పున్నమి ఘాట్ పార్కింగ్ & షటిల్ కేంద్రం',
    category_id: 'cat-parking',
    sector_id: 'sec-4',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6190, 16.5200] },
    status: 'ACTIVE',
    description: 'Spacious vehicle parking with direct free RTC shuttle to temple foot.',
    description_te: 'విశాలమైన కార్ల పార్కింగ్ మరియు ఉచిత RTC బస్సు సర్వీస్ సౌకర్యం.',
    address: 'Bhavanipuram Bypass Road, Vijayawada',
    address_te: 'భవానిపురం బైపాస్ రోడ్, విజయవాడ',
    contact_phone: '0866-2423640',
    contact_name: 'Parking Incharge',
    operating_hours: '24 Hours Open',
    capacity: 1200,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[1],
    sector: DEMO_SECTORS[3],
  },
  {
    id: 'loc-north-parking',
    name: 'Bhavani Ghat 4-Wheeler Parking Lot',
    name_te: 'భవాని ఘాట్ 4-వీలర్ పార్కింగ్ స్థలం',
    category_id: 'cat-parking',
    sector_id: 'sec-5',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6190, 16.5130] },
    status: 'ACTIVE',
    description: 'Designated parking for cars and private buses with security surveillance.',
    description_te: 'కార్లు మరియు ప్రైవేట్ బస్సుల కోసం ప్రత్యేక సిసిటివి రక్షణ పార్కింగ్.',
    address: 'Near NH65 Kummaripalem Junction',
    address_te: 'కుమ్మరిపాలెం జంక్షన్ సమీపంలో',
    contact_phone: '0866-2423641',
    contact_name: 'Traffic Supervisor',
    operating_hours: '24 Hours Open',
    capacity: 800,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[1],
    sector: DEMO_SECTORS[4],
  },
  {
    id: 'loc-medical-camp',
    name: 'Emergency Medical Station & 108 Base',
    name_te: 'అత్యవసర వైద్య కేంద్రం మరియు 108 బేస్',
    category_id: 'cat-medical',
    sector_id: 'sec-1',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6240, 16.5152] },
    status: 'ACTIVE',
    description: 'Equipped with doctors, oxygen cylinders, ICU ambulance and first aid kit.',
    description_te: 'డాక్టర్లు, ఆక్సిజన్ సిలిండర్లు మరియు 108 అంబులెన్స్‌తో కూడిన వైద్య శిబిరం.',
    address: 'Near Temple Rajagopuram, Indrakeeladri',
    address_te: 'రాజగోపురం సమీపంలో, ఇంద్రకీలాద్రి',
    contact_phone: '108',
    contact_name: 'Duty Medical Officer',
    operating_hours: '24 Hours Active',
    capacity: 50,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[3],
    sector: DEMO_SECTORS[0],
  },
  {
    id: 'loc-police-sos',
    name: 'Police Command & Child Safety Booth',
    name_te: 'పోలీస్ కమాండ్ & చిన్నారుల రక్షణ కేంద్రం',
    category_id: 'cat-medical',
    sector_id: 'sec-2',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6230, 16.5142] },
    status: 'ACTIVE',
    description: 'Police assistance, missing person tracing, lost & found counter and SOS help.',
    description_te: 'పోలీస్ సహాయం, తప్పిపోయిన వారి వివరాలు మరియు తక్షణ SOS సేవలు.',
    address: 'Hill Road Arch Base, Mallikarjunapeta',
    address_te: 'కొండ ఆర్చ్ దిగువన, మల్లికార్జునపేట',
    contact_phone: '100',
    contact_name: 'Sub-Inspector on Duty',
    operating_hours: '24 Hours Active',
    capacity: null,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[3],
    sector: DEMO_SECTORS[1],
  },
  {
    id: 'loc-prasadam-counter',
    name: 'Special Laddu & Prasadam Counters',
    name_te: 'ప్రత్యేక లడ్డూ & ప్రసాదం కౌంటర్లు',
    category_id: 'cat-food',
    sector_id: 'sec-1',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6242, 16.5145] },
    status: 'ACTIVE',
    description: 'Famous Kanaka Durga laddu prasadam counters with fast QR payment.',
    description_te: 'ప్రసిద్ధ కనకదుర్గ లడ్డూ మరియు పులిహోర ప్రసాదం కౌంటర్లు.',
    address: 'Temple Exit Quadrangle, Indrakeeladri',
    address_te: 'ఆలయ నిష్క్రమణ ప్రాంగణం, ఇంద్రకీలాద్రి',
    contact_phone: '0866-2423600',
    contact_name: 'Prasadam Officer',
    operating_hours: '05:00 AM - 10:00 PM',
    capacity: 50000,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 9,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[2],
    sector: DEMO_SECTORS[0],
  },
  {
    id: 'loc-bus-station',
    name: 'RTC Free Pilgrim Shuttle Terminal',
    name_te: 'RTC ఉచిత భక్త షటిల్ టెర్మినల్',
    category_id: 'cat-bus',
    sector_id: 'sec-3',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6205, 16.5175] },
    status: 'ACTIVE',
    description: 'Electric AC and Non-AC free shuttles connecting Railway station and bus stand.',
    description_te: 'రైల్వే స్టేషన్ మరియు బస్టాండ్ నుండి నిరంతర ఉచిత ఎలక్ట్రిక్ బస్సులు.',
    address: 'Near Old Toll Gate, Canal Road',
    address_te: 'పాత టోల్ గేట్ సమీపంలో, కెనాల్ రోడ్',
    contact_phone: '0866-2423660',
    contact_name: 'APSRTC Coordinator',
    operating_hours: '24 Hours Active',
    capacity: 10000,
    is_accessible: true,
    is_demo_data: true,
    metadata: {},
    display_order: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[4],
    sector: DEMO_SECTORS[2],
  },
];

export const DEMO_DARSHAN_QUEUES: DarshanQueue[] = [
  {
    id: 'q-general',
    location_id: '56b5d4a0-4a2c-427a-bc52-ff93eb120ddf',
    name: 'Dharma Darshan (Free Queue)',
    name_te: 'ధర్మ దర్శనం (ఉచిత క్యూ)',
    queue_type: 'GENERAL',
    status: 'OPEN',
    current_count: 1420,
    max_capacity: 4000,
    estimated_wait_minutes: 75,
    entry_point: { type: 'Point', coordinates: [80.6225, 16.5160] },
    exit_point: { type: 'Point', coordinates: [80.6242, 16.5145] },
    notes: 'Continuous flow with free drinking water & butter milk distributed in sheds.',
    notes_te: 'క్యూ లైన్లలో నిరంతర త్రాగునీరు మరియు మజ్జిగ సరఫరా చేయబడుతోంది.',
    is_demo_data: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[0],
  },
  {
    id: 'q-special-100',
    location_id: 'loc-ghat-queue',
    name: 'Special Darshan (₹100 Ticket)',
    name_te: 'ప్రత్యేక దర్శనం (₹100 టికెట్)',
    queue_type: 'SPECIAL',
    status: 'OPEN',
    current_count: 650,
    max_capacity: 2500,
    estimated_wait_minutes: 35,
    entry_point: { type: 'Point', coordinates: [80.6235, 16.5140] },
    exit_point: { type: 'Point', coordinates: [80.6242, 16.5145] },
    notes: 'Direct queue via Ghat Road staircase with barricades.',
    notes_te: 'ఘాట్ రోడ్ మెట్ల మార్గం ద్వారా త్వరిత దర్శన క్యూ.',
    is_demo_data: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[1],
  },
  {
    id: 'q-vip-300',
    location_id: 'loc-ghat-queue',
    name: 'Shighra Darshan (₹300 Ticket)',
    name_te: 'శీఘ్ర దర్శనం (₹300 టికెట్)',
    queue_type: 'VIP',
    status: 'OPEN',
    current_count: 210,
    max_capacity: 1000,
    estimated_wait_minutes: 15,
    entry_point: { type: 'Point', coordinates: [80.6235, 16.5140] },
    exit_point: { type: 'Point', coordinates: [80.6242, 16.5145] },
    notes: 'Express access to Mukha Mandapam parikrama.',
    notes_te: 'ముఖ మండపానికి నేరుగా శీఘ్ర ప్రవేశం.',
    is_demo_data: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[1],
  },
  {
    id: 'q-divyang',
    location_id: '56b5d4a0-4a2c-427a-bc52-ff93eb120ddf',
    name: 'Senior Citizens & Divyang Line',
    name_te: 'వృద్ధులు మరియు దివ్యాంగుల ప్రత్యేక లైన్',
    queue_type: 'DIVYANG',
    status: 'OPEN',
    current_count: 35,
    max_capacity: 300,
    estimated_wait_minutes: 10,
    entry_point: { type: 'Point', coordinates: [80.6238, 16.5148] },
    exit_point: { type: 'Point', coordinates: [80.6242, 16.5145] },
    notes: 'Battery buggy and wheelchair service available at Om Turning point.',
    notes_te: 'ఓం టర్నింగ్ వద్ద బ్యాటరీ కార్లు మరియు వీల్‌చైర్ సదుపాయం కలదు.',
    is_demo_data: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[0],
  },
];

export const DEMO_PARKING_AREAS: ParkingArea[] = [
  {
    id: 'pk-1',
    location_id: 'loc-north-parking',
    name: 'Bhavani Ghat 4-Wheeler Parking',
    name_te: 'భవాని ఘాట్ 4-వీలర్ పార్కింగ్',
    parking_type: 'PUBLIC',
    vehicle_types: ['CAR', 'SUV'],
    total_capacity: 500,
    area_geometry: null,
    entrance_point: null,
    contact_phone: '0866-2423641',
    is_paid: false,
    fee_info: null,
    is_demo_data: true,
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    current_status: {
      id: 'pks-1',
      parking_area_id: 'pk-1',
      occupied: 380,
      available: 120,
      status: 'AVAILABLE',
      data_source: 'MANUAL',
      updated_by: null,
      updated_at: new Date().toISOString(),
    },
    location: DEMO_LOCATIONS[5],
  },
  {
    id: 'pk-2',
    location_id: 'loc-punnami-ghat',
    name: 'Punnami Ghat Bypass Parking',
    name_te: 'పున్నమి ఘాట్ బైపాస్ పార్కింగ్',
    parking_type: 'PUBLIC',
    vehicle_types: ['CAR', 'BUS'],
    total_capacity: 300,
    area_geometry: null,
    entrance_point: null,
    contact_phone: '0866-2423640',
    is_paid: false,
    fee_info: null,
    is_demo_data: true,
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    current_status: {
      id: 'pks-2',
      parking_area_id: 'pk-2',
      occupied: 275,
      available: 25,
      status: 'FILLING',
      data_source: 'CAMERA',
      updated_by: null,
      updated_at: new Date().toISOString(),
    },
    location: DEMO_LOCATIONS[4],
  },
  {
    id: 'pk-3',
    location_id: null,
    name: 'Kummaripalem 2-Wheeler Stand',
    name_te: 'కుమ్మరిపాలెం 2-వీలర్ స్టాండ్',
    parking_type: 'PUBLIC',
    vehicle_types: ['BIKE', 'SCOOTER'],
    total_capacity: 800,
    area_geometry: null,
    entrance_point: null,
    contact_phone: null,
    is_paid: false,
    fee_info: null,
    is_demo_data: true,
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    current_status: {
      id: 'pks-3',
      parking_area_id: 'pk-3',
      occupied: 790,
      available: 10,
      status: 'FULL',
      data_source: 'MANUAL',
      updated_by: null,
      updated_at: new Date().toISOString(),
    },
  },
];

export const DEMO_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Free APSRTC Devotee Shuttles Operating from Bhavani Ghat',
    title_te: 'భవాని ఘాట్ నుండి ఉచిత ఆర్టీసీ షటిల్ బస్సులు నడుస్తున్నాయి',
    message: 'Continuous buses run every 3 minutes directly to the Indrakeeladri base. Devotees are requested to avoid private vehicles on Ghat road.',
    message_te: 'ప్రతి 3 నిమిషాలకు భవాని ఘాట్ నుండి నేరుగా కొండ కిందకు బస్సులు నడుస్తున్నాయి. ఘాట్ రోడ్డుపై ప్రైవేట్ వాహనాలు అనుమతించబడవు.',
    priority: 'URGENT',
    status: 'ACTIVE',
    target_audience: 'ALL',
    sector_id: null,
    starts_at: new Date().toISOString(),
    expires_at: null,
    created_by: null,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ann-2',
    title: '24x7 Hot Annadanam Meals Active at Annadanam Hall',
    title_te: 'అన్నదాన భవనంలో 24 గంటలు నిరంతర అన్నప్రసాదం అందుబాటులో ఉంది',
    message: 'Fresh sanctified meals and drinking water are available continuously for all visiting pilgrims without any coupon.',
    message_te: 'ఎటువంటి కూపన్లు లేకుండా భక్తులందరికీ తాజా అన్నప్రసాదం మరియు మంచినీరు ఉచితంగా అందించబడుతుంది.',
    priority: 'INFO',
    status: 'ACTIVE',
    target_audience: 'ALL',
    sector_id: null,
    starts_at: new Date().toISOString(),
    expires_at: null,
    created_by: null,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ann-3',
    title: 'Ghat Road Private Vehicle Movement Temporarily Suspended',
    title_te: 'ఘాట్ రోడ్డుపై ప్రైవేట్ వాహనాల రాకపోకలు తాత్కాలికంగా నిలిపివేయబడ్డాయి',
    message: 'In view of heavy crowd movement, only temple emergency vehicles and authorized buses are allowed on Ghat Road.',
    message_te: 'రద్దీ దృష్ట్యా ఘాట్ రోడ్డుపై కేవలం అత్యవసర వాహనాలు మరియు అధికారిక బస్సులు మాత్రమే అనుమతించబడుతున్నాయి.',
    priority: 'WARNING',
    status: 'ACTIVE',
    target_audience: 'ALL',
    sector_id: null,
    starts_at: new Date().toISOString(),
    expires_at: null,
    created_by: null,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_EMERGENCY_POINTS: EmergencyPoint[] = [
  {
    id: 'em-1',
    location_id: 'loc-medical-camp',
    emergency_type: 'MEDICAL',
    name: 'Indrakeeladri Hilltop Medical Aid Post',
    name_te: 'ఇంద్రకీలాద్రి కొండపై వైద్య శిబిరం',
    contact_phone: '108',
    contact_phone_2: null,
    status: 'ACTIVE',
    is_24h: true,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[6],
  },
  {
    id: 'em-2',
    location_id: 'loc-police-sos',
    emergency_type: 'POLICE',
    name: 'Mallikarjunapeta Police Control & Lost Child Desk',
    name_te: 'మల్లికార్జునపేట పోలీస్ కంట్రోల్ రూమ్',
    contact_phone: '100',
    contact_phone_2: null,
    status: 'ACTIVE',
    is_24h: true,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[7],
  },
];

export const DEMO_ROUTE_CLOSURES: RouteClosure[] = [
  {
    id: 'rc-1',
    title: 'Ghat Road Private Vehicle Movement Suspended',
    title_te: 'ఘాట్ రోడ్డు ప్రైవేట్ వాహన రాకపోకలు నిలిపివేత',
    closure_type: 'VEHICLE',
    status: 'ACTIVE',
    affected_area: null,
    closure_line: null,
    waypoints: null,
    reason: 'Heavy pedestrian foot traffic along hill curves',
    reason_te: 'కొండ మలుపుల వద్ద భక్తుల రద్దీ ఎక్కువగా ఉండటం వల్ల',
    start_time: new Date().toISOString(),
    end_time: null,
    created_by: null,
    sector_id: null,
    sub_sector_id: null,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
