import type {
  Location,
  Sector,
  DarshanQueue,
  ParkingArea,
  Announcement,
  EmergencyPoint,
  RouteClosure,
  LocationCategory
} from '@/types';

export const DEMO_CATEGORIES: LocationCategory[] = [
  { id: 'cat-darshan', slug: 'darshan', name: 'Darshan & Queues', name_te: 'దర్శనం మరియు క్యూలు', icon: 'Eye', color: '#9b1b30', is_primary: true, display_order: 1, created_at: new Date().toISOString() },
  { id: 'cat-parking', slug: 'parking', name: 'Vehicle Parking', name_te: 'వాహన పార్కింగ్', icon: 'Car', color: '#2563eb', is_primary: true, display_order: 2, created_at: new Date().toISOString() },
  { id: 'cat-food', slug: 'food', name: 'Annadanam & Meals', name_te: 'అన్నదానం మరియు భోజనం', icon: 'Utensils', color: '#ea580c', is_primary: true, display_order: 3, created_at: new Date().toISOString() },
  { id: 'cat-medical', slug: 'medical', name: 'Medical & First Aid', name_te: 'వైద్యం మరియు ప్రథమ చికిత్స', icon: 'Plus', color: '#dc2626', is_primary: true, display_order: 4, created_at: new Date().toISOString() },
  { id: 'cat-bus', slug: 'bus', name: 'RTC Shuttle & Bus', name_te: 'RTC షటిల్ మరియు బస్సు', icon: 'Bus', color: '#059669', is_primary: true, display_order: 5, created_at: new Date().toISOString() },
  { id: 'cat-ghat', slug: 'ghat', name: 'River Ghats & Bathing', name_te: 'నది ఘాట్లు మరియు స్నాన ఘట్టాలు', icon: 'Waves', color: '#0284c7', is_primary: false, display_order: 6, created_at: new Date().toISOString() },
];

// Simplified DEMO_SECTORS — no slug, status, crowd, coordinates, display_order
export const DEMO_SECTORS: Sector[] = [
  {
    id: 'sec-1',
    name: 'Sector 1 — Indrakeeladri Hill Top Sanctum',
    name_te: 'సెక్టార్ 1 — ఇంద్రకీలాద్రి కొండపై గర్భగుడి',
    description: 'Main temple shrine, sanctum sanctorum and sanctified parikrama.',
    description_te: 'ప్రధాన ఆలయ గర్భాలయం మరియు పరిక్రమ ప్రాంగణం.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-2',
    name: 'Sector 2 — Ghat Road Queue Complex',
    name_te: 'సెక్టార్ 2 — ఘాట్ రోడ్ క్యూ కాంప్లెక్స్',
    description: 'Covered queue lines along Indrakeeladri Ghat Road.',
    description_te: 'ఇంద్రకీలాద్రి ఘాట్ రోడ్ వెంబడి ఉన్న రక్షిత క్యూ లైన్లు.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-3',
    name: 'Sector 3 — Hill Base & Annadanam Complex',
    name_te: 'సెక్టార్ 3 — కొండ దిగువ మరియు అన్నదానం కాంప్లెక్స్',
    description: 'Foot-hill entrance, shoe stands, luggage counters and Annadanam.',
    description_te: 'కొండ దిగువ ప్రవేశ ద్వారం, పాదరక్షల స్టాండ్ మరియు అన్నదాన భవనం.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-4',
    name: 'Sector 4 — Krishna River Bathing Ghats',
    name_te: 'సెక్టార్ 4 — కృష్ణా నది స్నాన ఘట్టాలు',
    description: 'Bhavani Ghat, Punnami Ghat, dressing rooms and holy bath areas.',
    description_te: 'భవాని ఘాట్, పున్నమి ఘాట్ మరియు పవిత్ర స్నాన ప్రాంతాలు.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sec-5',
    name: 'Sector 5 — Outer Transit & Parking Hubs',
    name_te: 'సెక్టార్ 5 — బాహ్య రవాణా మరియు పార్కింగ్ కేంద్రాలు',
    description: 'NH65 parking grounds and free APSRTC shuttle hubs.',
    description_te: 'NH65 పార్కింగ్ స్థలాలు మరియు ఉచిత RTC షటిల్ స్టేషన్లు.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Simplified DEMO_LOCATIONS — no contact, status, operating_hours, accessibility, display_order
export const DEMO_LOCATIONS: Location[] = [
  {
    id: '56b5d4a0-4a2c-427a-bc52-ff93eb120ddf',
    name: 'Main Darshan Entry (Indrakeeladri Hill Top)',
    name_te: 'ప్రధాన దర్శన ప్రవేశం (ఇంద్రకీలాద్రి కొండపై)',
    category_id: 'cat-darshan',
    sector_id: 'sec-1',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6238, 16.5148] },
    description: 'Primary entry point to the inner sanctum of Sri Kanaka Durga Ammavaru.',
    address: 'Indrakeeladri Hill, Mallikarjunapeta, Vijayawada',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[0],
    sector: DEMO_SECTORS[0],
  },
  {
    id: 'loc-ghat-queue',
    name: 'Ghat Road Queue Complex Entry',
    name_te: 'ఘాట్ రోడ్ క్యూ కాంప్లెక్స్ ప్రవేశం',
    category_id: 'cat-darshan',
    sector_id: 'sec-2',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6235, 16.5140] },
    description: 'Special ₹100 and ₹300 queue line entrance along shaded ghat steps.',
    address: 'Ghat Road curve 2, Indrakeeladri',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[0],
    sector: DEMO_SECTORS[1],
  },
  {
    id: 'loc-annadanam',
    name: '24x7 Maha Annadanam Bhavan',
    name_te: '24x7 మహా అన్నదాన భవనం',
    category_id: 'cat-food',
    sector_id: 'sec-3',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6225, 16.5160] },
    description: 'Free sanctified vegetarian meals served continuously for all visiting pilgrims.',
    address: 'Opposite Hill Steps Entrance, Vijayawada',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[2],
    sector: DEMO_SECTORS[2],
  },
  {
    id: 'loc-bhavani-ghat',
    name: 'Bhavani Ghat Holy Bathing & Transit',
    name_te: 'భవాని ఘాట్ పవిత్ర స్నాన ఘట్టం & రవాణా',
    category_id: 'cat-ghat',
    sector_id: 'sec-4',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6210, 16.5180] },
    description: 'Sacred Krishna river bathing ghat with locker rooms and shuttle pickup.',
    address: 'Krishna Riverbank, Near Prakasam Barrage',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[5],
    sector: DEMO_SECTORS[3],
  },
  {
    id: 'loc-punnami-ghat',
    name: 'Punnami Ghat Parking & Shuttle Hub',
    name_te: 'పున్నమి ఘాట్ పార్కింగ్ & షటిల్ కేంద్రం',
    category_id: 'cat-parking',
    sector_id: 'sec-4',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6190, 16.5200] },
    description: 'Spacious vehicle parking with direct free RTC shuttle to temple foot.',
    address: 'Bhavanipuram Bypass Road, Vijayawada',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[1],
    sector: DEMO_SECTORS[3],
  },
  {
    id: 'loc-north-parking',
    name: 'Bhavani Ghat 4-Wheeler Parking Lot',
    name_te: 'భవాని ఘాట్ 4-వీలర్ పార్కింగ్ స్థలం',
    category_id: 'cat-parking',
    sector_id: 'sec-5',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6190, 16.5130] },
    description: 'Designated parking for cars and private buses with security surveillance.',
    address: 'Near NH65 Kummaripalem Junction',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[1],
    sector: DEMO_SECTORS[4],
  },
  {
    id: 'loc-medical-camp',
    name: 'Emergency Medical Station & 108 Base',
    name_te: 'అత్యవసర వైద్య కేంద్రం మరియు 108 బేస్',
    category_id: 'cat-medical',
    sector_id: 'sec-1',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6240, 16.5152] },
    description: 'Equipped with doctors, oxygen cylinders, ICU ambulance and first aid kit.',
    address: 'Near Temple Rajagopuram, Indrakeeladri',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[3],
    sector: DEMO_SECTORS[0],
  },
  {
    id: 'loc-police-sos',
    name: 'Police Command & Child Safety Booth',
    name_te: 'పోలీస్ కమాండ్ & చిన్నారుల రక్షణ కేంద్రం',
    category_id: 'cat-medical',
    sector_id: 'sec-2',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6230, 16.5142] },
    description: 'Police assistance, missing person tracing, lost & found counter and SOS help.',
    address: 'Hill Road Arch Base, Mallikarjunapeta',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[3],
    sector: DEMO_SECTORS[1],
  },
  {
    id: 'loc-prasadam-counter',
    name: 'Special Laddu & Prasadam Counters',
    name_te: 'ప్రత్యేక లడ్డూ & ప్రసాదం కౌంటర్లు',
    category_id: 'cat-food',
    sector_id: 'sec-1',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6242, 16.5145] },
    description: 'Famous Kanaka Durga laddu prasadam counters with fast QR payment.',
    address: 'Temple Exit Quadrangle, Indrakeeladri',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[2],
    sector: DEMO_SECTORS[0],
  },
  {
    id: 'loc-bus-station',
    name: 'RTC Free Pilgrim Shuttle Terminal',
    name_te: 'RTC ఉచిత భక్త షటిల్ టెర్మినల్',
    category_id: 'cat-bus',
    sector_id: 'sec-3',
    sub_sector_id: null,
    position: { type: 'Point', coordinates: [80.6205, 16.5175] },
    description: 'Electric AC and Non-AC free shuttles connecting Railway station and bus stand.',
    address: 'Near Old Toll Gate, Canal Road',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: DEMO_CATEGORIES[4],
    sector: DEMO_SECTORS[2],
  },
];

export const DEMO_DARSHAN_QUEUES: DarshanQueue[] = [
  {
    id: 'q-general',
    location_id: '56b5d4a0-4a2c-427a-bc52-ff93eb120ddf',
    name: 'Dharma Darshan (Free Queue)',
    name_te: 'ధర్మ దర్శనం (ఉచిత క్యూ)',
    queue_type: 'GENERAL',
    status: 'OPEN',
    current_count: 1420,
    max_capacity: 4000,
    estimated_wait_minutes: 75,
    entry_point: { type: 'Point', coordinates: [80.6225, 16.5160] },
    exit_point: { type: 'Point', coordinates: [80.6242, 16.5145] },
    notes: 'Continuous flow with free drinking water & butter milk distributed in sheds.',
    notes_te: 'క్యూ లైన్లలో నిరంతర త్రాగునీరు మరియు మజ్జిగ సరఫరా చేయబడుతోంది.',
    is_demo_data: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[0],
  },
  {
    id: 'q-special-100',
    location_id: 'loc-ghat-queue',
    name: 'Special Darshan (₹100 Ticket)',
    name_te: 'ప్రత్యేక దర్శనం (₹100 టికెట్)',
    queue_type: 'SPECIAL',
    status: 'OPEN',
    current_count: 650,
    max_capacity: 2500,
    estimated_wait_minutes: 35,
    entry_point: { type: 'Point', coordinates: [80.6235, 16.5140] },
    exit_point: { type: 'Point', coordinates: [80.6242, 16.5145] },
    notes: 'Direct queue via Ghat Road staircase with barricades.',
    notes_te: 'ఘాట్ రోడ్ మెట్ల మార్గం ద్వారా త్వరిత దర్శన క్యూ.',
    is_demo_data: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[1],
  },
  {
    id: 'q-vip-300',
    location_id: 'loc-ghat-queue',
    name: 'Shighra Darshan (₹300 Ticket)',
    name_te: 'శీఘ్ర దర్శనం (₹300 టికెట్)',
    queue_type: 'VIP',
    status: 'OPEN',
    current_count: 210,
    max_capacity: 1000,
    estimated_wait_minutes: 15,
    entry_point: { type: 'Point', coordinates: [80.6235, 16.5140] },
    exit_point: { type: 'Point', coordinates: [80.6242, 16.5145] },
    notes: 'Express access to Mukha Mandapam parikrama.',
    notes_te: 'ముఖ మండపానికి నేరుగా శీఘ్ర ప్రవేశం.',
    is_demo_data: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[1],
  },
  {
    id: 'q-divyang',
    location_id: '56b5d4a0-4a2c-427a-bc52-ff93eb120ddf',
    name: 'Senior Citizens & Divyang Line',
    name_te: 'వృద్ధులు మరియు దివ్యాంగుల ప్రత్యేక లైన్',
    queue_type: 'DIVYANG',
    status: 'OPEN',
    current_count: 35,
    max_capacity: 300,
    estimated_wait_minutes: 10,
    entry_point: { type: 'Point', coordinates: [80.6238, 16.5148] },
    exit_point: { type: 'Point', coordinates: [80.6242, 16.5145] },
    notes: 'Battery buggy and wheelchair service available at Om Turning point.',
    notes_te: 'ఓం టర్నింగ్ వద్ద బ్యాటరీ కార్లు మరియు వీల్‌చైర్ సదుపాయం కలదు.',
    is_demo_data: true,
    updated_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[0],
  },
];

export const DEMO_PARKING_AREAS: ParkingArea[] = [
  {
    id: 'park-punnami',
    location_id: 'loc-punnami-ghat',
    name: 'Punnami Ghat Parking Area',
    name_te: 'పున్నమి ఘాట్ పార్కింగ్ ప్రాంతం',
    parking_type: 'PUBLIC',
    vehicle_types: ['TWO_WHEELER', 'CAR', 'BUS'],
    total_capacity: 1200,
    area_geometry: null,
    entrance_point: { type: 'Point', coordinates: [80.6188, 16.5200] },
    contact_phone: '0866-2423640',
    is_paid: false,
    fee_info: null,
    is_demo_data: true,
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[4],
    current_status: {
      id: 'ps-punnami',
      parking_area_id: 'park-punnami',
      occupied: 780,
      available: 420,
      status: 'FILLING',
      data_source: 'MANUAL',
      updated_by: null,
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'park-north',
    location_id: 'loc-north-parking',
    name: 'Bhavani Ghat 4-Wheeler Parking',
    name_te: 'భవాని ఘాట్ 4-వీలర్ పార్కింగ్',
    parking_type: 'PUBLIC',
    vehicle_types: ['CAR', 'BUS'],
    total_capacity: 800,
    area_geometry: null,
    entrance_point: { type: 'Point', coordinates: [80.6188, 16.5130] },
    contact_phone: '0866-2423641',
    is_paid: false,
    fee_info: null,
    is_demo_data: true,
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[5],
    current_status: {
      id: 'ps-north',
      parking_area_id: 'park-north',
      occupied: 320,
      available: 480,
      status: 'AVAILABLE',
      data_source: 'MANUAL',
      updated_by: null,
      updated_at: new Date().toISOString(),
    },
  },
];

export const DEMO_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-welcome',
    title: 'Welcome to Dasara at Sri Kanaka Durga Temple',
    title_te: 'శ్రీ కనక దుర్గమ్మ ఆలయంలో దసరాకు స్వాగతం',
    message: 'Welcome to the Dasara festival. This app will help you navigate the temple premises safely and efficiently.',
    message_te: 'దసరా పండుగకు స్వాగతం. ఈ యాప్ ఆలయ ప్రాంగణంలో సురక్షితంగా మరియు సమర్థంగా నావిగేట్ చేయడంలో మీకు సహాయపడుతుంది.',
    priority: 'INFO',
    status: 'ACTIVE',
    target_audience: 'ALL',
    sector_id: null,
    starts_at: new Date(Date.now() - 3600000).toISOString(),
    expires_at: null,
    created_by: null,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ann-queue',
    title: 'Test: Darshan queue 2 is now open',
    title_te: 'పరీక్ష: దర్శన క్యూ 2 ఇప్పుడు తెరవబడింది',
    message: 'Current estimated wait time for general darshan is approximately 75 minutes.',
    message_te: 'సాధారణ దర్శనానికి ప్రస్తుత అంచనా నిరీక్షణ సమయం దాదాపు 75 నిమిషాలు.',
    priority: 'NOTICE',
    status: 'ACTIVE',
    target_audience: 'ALL',
    sector_id: null,
    starts_at: new Date(Date.now() - 1800000).toISOString(),
    expires_at: null,
    created_by: null,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_EMERGENCY_POINTS: EmergencyPoint[] = [
  {
    id: 'ep-police',
    location_id: 'loc-police-sos',
    emergency_type: 'POLICE',
    name: 'Police Command Booth Alpha',
    name_te: 'పోలీస్ కమాండ్ బూత్ ఆల్ఫా',
    contact_phone: '100',
    contact_phone_2: null,
    is_24h: true,
    status: 'ACTIVE',
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[7],
  },
  {
    id: 'ep-medical',
    location_id: 'loc-medical-camp',
    emergency_type: 'MEDICAL',
    name: 'Base Medical Camp',
    name_te: 'బేస్ మెడికల్ క్యాంప్',
    contact_phone: '108',
    contact_phone_2: null,
    is_24h: true,
    status: 'ACTIVE',
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    location: DEMO_LOCATIONS[6],
  },
];

export const DEMO_ROUTE_CLOSURES: RouteClosure[] = [
  {
    id: 'closure-demo-1',
    title: '[DEMO] Ghat Road Partial Restriction',
    title_te: '[డెమో] ఘాట్ రోడ్ పాక్షిక నిబంధన',
    reason: 'DEMO: Heavy pilgrim footfall. Vehicle movement restricted on ghat road between 6 AM and 10 PM.',
    reason_te: 'డెమో: అధిక భక్తుల రద్దీ. ఘాట్ రోడ్‌పై వాహన రాకపోకలు ఉ.6 నుండి రా.10 వరకు నిషేధించబడ్డాయి.',
    closure_type: 'VEHICLE',
    affected_area: null,
    closure_line: null,
    waypoints: null,
    status: 'ACTIVE',
    start_time: new Date(Date.now() - 7200000).toISOString(),
    end_time: null,
    created_by: null,
    sector_id: null,
    sub_sector_id: null,
    is_demo_data: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
